name: Centos

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  centos:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version:
          - 1.0.1
          - 1.0.0
      fail-fast: false
    steps:
      - run: docker run --name centos bash -c "yum -y update && yum -y install curl git"
      #- run: sudo apt-get update && sudo apt-get install -y curl git
      #- run: curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/${{ matrix.version }}/setup.sh" | bash
      #- run: test "$(bpkg --version)" = "${{ matrix.version }}"
