name: Ubuntu Bionic Beaver

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-bionic:
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{ fromJson('version.json') }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y ${{ matrix.shells.package }}
      - run: sudo ${{ matrix.shells.shell }} ./shellspec --task fixture:stat:prepare
      - run: SH="${{ matrix.shells.shell }}" contrib/various_test.sh
