name: Ubuntu Bionic Beaver

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-bionic:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version:
          - 1.0.1
          - 1.0.0
      fail-fast: false
    steps:
      - run: apt-get update && apt-get install -y curl git
      - run: curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/${{ matrix.version }}/setup.sh" | bash
      - run: test "$(bpkg --version)" = "${{ matrix.version }}"
