name: Windows MSYS

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  setup:
    runs-on: windows-latest
    

    strategy:
      matrix:
        version:
          - 1.0.1
          - 1.0.0
      fail-fast: false
    steps:
      - run: pacman.exe -S --noprogressbar --noconfirm
      - run: curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/${{ matrix.version }}/setup.sh" | bash
      - run: test "$(bpkg --version)" = "${{ matrix.version }}"
