name: Windows MSYS

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  setup:
    runs-on: windows-latest
    

    strategy:
      matrix:
        version:
          - 1.0.1
          - 1.0.0
      fail-fast: false
    steps:
      - run: echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: set
      - run: "dir env:"
      - run: curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/${{ matrix.version }}/setup.sh" | bash
      - run: test "$(bpkg --version)" = "${{ matrix.version }}"

